name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use secret in script
        run: echo "My secret is $MY_SECRET"
        env:
          # MY_SECRET: ${{ secrets.API_KEY }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          SECRET_PW1: ${{ secrets.SECRET_PW1 }}
          SECRET_PW2: ${{ secrets.SECRET_PW2 }}
